### ISSUE TITLE
Pull Request Club

### ISSUE THREAD

**Issue by yewtc** [reneeb/Types-RENEEB#5]
Hi, I've been assigned  this module via the pull request  club but can't install it because OTRS::OPM::Parser comes up as not being found  - am I doing something wrong?

**Comment by reneeb** [comment]
Hi @yewtc , no, you're not doing anything wrong. I should have done a few changes. We do not use OTRS any longer as they shut down the community version. Nowadays, I avoid using OTRS in any module names. So there is a successor for OTRS::OPM::Parser, it's called [OPM::Parser](https://metacpan.org/pod/OPM::Parser).

So, one pull request could be an update of the prereq list ;-)

BTW. Thanks for being part of Pull Request Club. I already had some nice and helpful contributions of its members...

**Comment by yewtc** [comment]
So that works - but it begs the question why have Types::OTRS any more?

**Comment by reneeb** [comment]
Yeah, it should be renamed/changed to Types::OPM...

**Comment by yewtc** [comment]
Is  OPMVersion* still of any value?

**Comment by reneeb** [comment]
Yes it is. There are (at least) two forks of OTRS (namely [Znuny](https://znuny.org/) and [OTOBO](https://otobo.de)) that use the same versioning schema.
